# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-18 16:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.TextField(blank=True, help_text='expand on the title')),
                ('text', models.TextField(blank=True, help_text='add text')),
                ('pub_date', models.DateTimeField(help_text='add date that will be displayed and used for sorting', verbose_name='date published')),
                ('image', models.ImageField(blank=True, help_text='add image that will be displayed', max_length=500, upload_to='./')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='tag',
            field=models.ManyToManyField(help_text='add here tags if tags if useful. if they do not exist, click on plus symbol.', related_name='tag_post', to='home.Tag'),
        ),
    ]
