# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-07 13:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20170707_1254'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'permissions': (('can_see_forum', 'Can see forum'), ('cann_see_repository', 'Can vote in elections'), ('can_see_some_of_our_results', 'Can see some of our results'), ('can_see_private_files', 'Can see private_files'), ('can_see_all_proposals', 'Can see all proposals'), ('can_write_comments_on_proposals', 'Can write comments on proposals'))},
        ),
    ]
