# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-18 15:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20170707_1302'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='email_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='email_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
