# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-22 15:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20170718_1516'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('document', models.FileField(upload_to='documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposal_rationale', models.FileField(blank=True, help_text='this is the rationale of the proposal', upload_to='./')),
                ('proposal_technical_support', models.FileField(blank=True, help_text='this is the technical addendum of the proposal', upload_to='./')),
                ('respose_scientific_committee', models.TextField(blank=True, help_text='add text')),
                ('respose_steering_committee', models.TextField(blank=True, help_text='add text')),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='proposal',
            field=models.ManyToManyField(help_text='this is for the proposals', related_name='proposal', to='home.Proposal'),
        ),
    ]
