# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-23 01:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20170723_0103'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='proposal_title',
            field=models.CharField(blank=True, help_text='add comments, if any', max_length=1000),
        ),
    ]
