# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-23 01:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_proposal_proposal_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='proposal_title',
            field=models.CharField(help_text='Please insert the title of the proposal', max_length=1000),
        ),
    ]
