# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-23 12:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20170723_0107'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='proposal_ID',
            field=models.IntegerField(default=0),
        ),
    ]
