# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-23 14:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_proposal_proposal_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposal',
            name='proposal_reference_code',
        ),
    ]
