# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-23 14:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_auto_20170723_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='user_proposal',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
