# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-23 15:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_auto_20170723_1500'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposal',
            name='user_proposal',
        ),
    ]
