# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-23 15:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_auto_20170723_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='proposal_progressive_index',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='proposal_ID',
            field=models.CharField(max_length=100, null=True, verbose_name='code_of_the_proposal'),
        ),
    ]
