# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-23 23:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_auto_20170723_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='user_proposal',
            field=models.CharField(help_text='NeXT username of the proposer', max_length=1000, null=True, verbose_name='Name of the proposer'),
        ),
    ]
