# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-17 13:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FilesUploaded',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('fileUploaded', models.FileField(help_text='the file', upload_to='uploads/')),
                ('fileFormat', models.CharField(max_length=255)),
            ],
        ),
    ]
